# hostname (and path) to the root
baseURL: "https://vanillajspodcast.com"

# Customer parameters
params:
  description: "A show about JavaScript for people who hate the complexity of modern front‑end web development."
  email: "chris@gomakethings.com"
  owner: "Chris Ferdinandi"
  explicit: "yes"
  image: "https://vanillajspodcast.com/img/vanilla-js-podcast.jpg"
  api: "https://gomakethings.com/api/data.json"
  episodes: "https://api.soundcloud.com/users/422835952/tracks?client_id=9yZSvlXAK7Wmu4xhb0hdMtjP9D2z351X"
  itunes: "https://itunes.apple.com/us/podcast/the-vanilla-js-podcast/id1364574460"
  spotify: "https://open.spotify.com/show/2jfWVEgKGZMazgou1hXH1R?si=ZDcXluvvScWFMSfbaLgEwg"
  google: "https://podcasts.google.com/feed/aHR0cHM6Ly9nb21ha2V0aGluZ3MuY29tL3BvZGNhc3QvZmVlZC5yc3M"
  rssURL: "https://gomakethings.com/podcast/feed.rss"
  rssLimit: 7
  minify: true

# Caches
caches:
  getjson:
    maxAge: "5m"

# The language code for the site
languageCode: "en-us"

# Site title
title: "The Vanilla JS Podcast"

# theme to use (located by default in /themes/THEMENAME/)
theme: "gmt"

# Permalinks
# See "content-management/permalinks"
permalinks:
  episodes: /:title/

# Allows you to disable all page types and will render nothing related to 'kind';
# values = "page", "home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"
disableKinds: ["RSS", "hugoGeneratorInject", "404"]

# Files to ignore while rendering
ignoreFiles: []

# the length of text to show in a .Summary
summaryLength: 70

# Pagination
paginate: 35
paginatePath: "page"

# Markdown Options
blackfriday:
  fractions: false

# Site taxonomies
taxonomies:
  - category: "categories"
  - tag: "tags"